apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-backend
  template:
    metadata:
      labels:
        app: auth-backend
    spec:
      containers:
      - name: auth-backend
        image: hxn7/auth-api:1
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-backend
spec:
  selector:
    app: auth-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000