apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-backend
  template:
    metadata:
      labels:
        app: post-backend
    spec:
      containers:
      - name: post-backend
        image: hxn7/post-api:1
        ports:
        - containerPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: post-backend
spec:
  selector:
    app: post-backend
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002